### ISSUE TITLE
It appears as if the declared license and the actual license disagree with each other.

### ISSUE THREAD

**Issue by kat-co** [AccelerationNet/symbol-munger#5]
The ASDF package [specifies](https://github.com/AccelerationNet/symbol-munger/blob/master/symbol-munger.asd#L13) the license is [BSD](https://en.wikipedia.org/wiki/BSD_licenses); however, the verbiage in all the license comments and in the license file looks like it is the [MIT License](https://opensource.org/licenses/MIT). Can you please bring these into line with each other?

**Comment by bobbysmith007** [comment]
Yes I can, thanks for pointing that out.  I will fix it when I next get around to this, or I am happy to merge a patch either way
